### ISSUE TITLE
No warnings for unmatched compatibles ("-m")

### ISSUE THREAD

**Issue by krzk** [devicetree-org/dt-schema#122]
-m argument stopped working on 2023.09 and 2023.11 (did not look earlier).

1. Apply https://lore.kernel.org/r/20231212094900.12615-2-quic_tengfan@quicinc.com
2. Check the binding with -m:
```
make DT_CHECKER_FLAGS=-m dt_binding_check DT_SCHEMA_FILES=qcom,sm4450-tlmm.yaml 
```

Result: everything fine
Expected result: warning for unmatched compatible (qcom,sm4450-pinctrl is documented, not qcom,sm4450-tlmm)

**Comment by robherring** [comment]
The issue is the check is picking up compatible patterns from the qcom naming patterns schema. IOW, almost no qcom compatible is checked. I'm modifying the schema generation to skip any patterns which don't have both start and end anchors or have '.*' or '.+' in the pattern. That eliminates those patterns and a bunch from at24.yaml.
